---
- name: Reinstall YIO
  hosts: all
  connection: local

  vars_files:
    - vars/common.yml

  vars:
    yio_dir: "{{ ce_source_dir }}/libs/yio"

  tasks:

    - name: Build clang extension
      ansible.builtin.command:
        cmd: "make -C extensions/clang install B=/build_extensions_clang"
        chdir: "{{ yio_dir }}"
      changed_when: true

    - name: Build gcc extension
      ansible.builtin.command:
        cmd: "make -C extensions/gcc install B=/build_extensions_gcc"
        chdir: "{{ yio_dir }}"
      changed_when: true